version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    container_name: gvendas-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gvendas_db
  
  jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250 
      - 14268:14268 
      - 14269:14269 
      - 9411:9411

